const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('vektolab', {
  togglePanel: () => ipcRenderer.send('toggle-panel'),
  showAvatarMenu: () => ipcRenderer.send('show-avatar-menu'),
  closePanel: () => ipcRenderer.send('close-panel'),
  openGenerator: slug => ipcRenderer.send('open-generator', slug),
  openDesign: slug => ipcRenderer.send('open-design', slug),
  openCatalog: () => ipcRenderer.send('open-catalog'),
  closeCatalog: () => ipcRenderer.send('close-catalog'),
  closeGeneratorView: () => ipcRenderer.send('close-generator-view'),
  openSite: () => ipcRenderer.send('open-site'),
  setPanelOpen: open => ipcRenderer.send('set-panel-open', !!open),
  startAvatarDrag: (x, y) => ipcRenderer.send('avatar-drag-start', { x, y }),
  moveAvatarDrag: (x, y, vx, vy) => ipcRenderer.send('avatar-drag-move', { x, y, vx, vy }),
  endAvatarDrag: (vx, vy) => ipcRenderer.send('avatar-drag-end', { vx, vy }),
  quit: () => ipcRenderer.send('quit-app'),
  checkUpdates: () => ipcRenderer.send('check-updates'),
  syncContent: () => ipcRenderer.send('sync-content'),
  installUpdate: () => ipcRenderer.send('install-update'),
  onUpdateState: callback => ipcRenderer.on('update-state', (_event, state) => callback(state)),
  getUpdateState: () => ipcRenderer.send('get-update-state'),
  getContentState: () => ipcRenderer.send('get-content-state'),
  onContentState: callback => ipcRenderer.on('content-state', (_event, state) => callback(state)),
  getGenerators: () => ipcRenderer.send('get-generators'),
  onGenerators: callback => ipcRenderer.on('generators', (_event, list) => callback(list)),
  getDesigns: () => ipcRenderer.send('get-designs'),
  onDesigns: callback => ipcRenderer.on('designs', (_event, list) => callback(list)),
  onCatalogMode: callback => ipcRenderer.on('catalog-mode', callback),
  onAssistantBlur: callback => ipcRenderer.on('assistant-blur', callback),
  onGeneratorView: callback => ipcRenderer.on('generator-view', (_event, data) => callback(data)),
  getAppVersion: () => ipcRenderer.send('get-app-version'),
  onAppVersion: callback => ipcRenderer.on('app-version', (_event, version) => callback(version)),
  onPanelPlacement: callback => ipcRenderer.on('panel-placement', (_event, placement) => callback(placement)),
  onAvatarEdgeBounce: callback => ipcRenderer.on('avatar-edge-bounce', (_event, direction) => callback(direction))
});
